### ISSUE TITLE
das3_readosim.m: getLocationInParent no longer works

### ISSUE THREAD

**Issue by tvdbogert** [dasproject/DAS3#2]
model/das3_readosim.m:

getLocationInParent no longer works in Opensim 4.0, the values are now stored in the parent offset frame.  Code in model/das3_readosim.m must be changed to make this work again.

**Comment by derekwolf19** [comment]
I plan to update model/das3_readosim to fix this issue.

**Comment by tvdbogert** [comment]
Sounds good.  When you get to a point where you need another file, you can simply take it from the copy of the repository I gave you a few weeks ago.  Put it in the appropriate local github folder, and commit, and push origin.  I want to keep things organized roughly this way: the model folder has everything you need to use the model.  The build folder is what is needed to build the MEX function.  Users and developers both need the readosim function, so it's in the model folder.

When this issue is resolved, type a final comment and click "close and comment" below.

Create new issues as needed.

**Comment by dblana** [comment]
Hi @derekwolf19, I now have more time to help with this, so if you have any problems please let me know! :smiley:

**Comment by derekwolf19** [comment]
Thans @dblana! I am starting to dig into it now. There will be a bit of a learning curve for me, but I will let you know if I get bogged down!

**Comment by derekwolf19** [comment]
@dblana @tvdbogert I have das3_readosim running without errors. I did some quick glances through the model structure which is output, and I think it mostly makes sense. If you have a quick way to double check it, that would be great. 

One thing I did notice was that the number of constraints and markers were zero. I am not certain what those are supposed to be, or if that is an issue. If either of you have any idea what needs to change for those sections, please let me know.

If this file is complete/correct, the next step needed is the Autolev stuff to be run.

**Comment by tvdbogert** [comment]
@derekwolf19 @dblana I will close this issue because it's resolved (you showed me).  Will run the build script and post another issue that can be worked on.

**Comment by tvdbogert** [comment]
P.S. The marker numbers and constraints fields are created by Opensim and we don't use those.
