### ISSUE TITLE
Visual C++ 2015 can't compile the code

### ISSUE THREAD

**Issue by tvdbogert** [dasproject/DAS3#3]
Need to figure out which C compiler to use.  Error message:

Building with 'Microsoft Visual C++ 2015 (C)'.
Error using mex
das3_al.c
c:\users\ton\documents\github\das3\model\build\das3_al.c(61832) : fatal error C1002: compiler is out of heap space in pass 2

**Comment by tvdbogert** [comment]
@dblana Do you remember which C compiler we used?  I have managed to compile it, some time ago, with Matlab 64 bit but now it does not work.  I may have installed a new C compiler since then...

**Comment by dblana** [comment]
I'll check the compiler I have on the desktop (which is at home). I will try to compile the code as well, because I may also have installed a new C compiler recently 😬

**Comment by tvdbogert** [comment]
Thanks.  I just remembered that I uninstalled the MingW compilers, I suspect that this is what we actually used.  Will re-install and let you know how it goes.

**Comment by tvdbogert** [comment]
Currently trying the MinGW compiler (https://www.mathworks.com/matlabcentral/fileexchange/52848-matlab-support-for-mingw-w64-c-c-compiler)

Getting farther but some issues with memory allocation.  Will keep you informed.

**Comment by tvdbogert** [comment]
It works with the MinGW compiler.  Sometimes the compiler says "out of memory" but then it works when I restart Matlab.  My computer is old.  I have not completed a compilation without the -g option yet, it should take about 36 hours.  But for all development work we keep the -g option anyway.  Computation speed is not important until later.
